pipeline {
    agent { 
		dockerfile {
			filename 'Dockerfile'
			dir 'ci/Build'
			args '--entrypoint=\'\''
		}
	}
    stages {
        stage('Compile') {
            steps {
                sh 'mvn -f kotlin-hello-world clean install '
            }
        }
    }
}
