pipeline {
    agent { 
		dockerfile {
			filename 'Dockerfile'
			dir 'ci/Build'
			args '--entrypoint=\'\''
		}
	}
    stages {
        stage('Test') {
            steps {
                sh 'mvn -v'
            }
        }
    }
}
